### ISSUE TITLE
Can not download the datasets!!

### ISSUE THREAD

**Issue by SeanSiyang** [marionacaros/barlow-twins-for-sem-seg#1]
Hi,
after filling out the form, I received a download link in my email, but when I clicked on the Google link, I was prompted that the file did not exist.

Can you confirm it? I cannot download the dataset. Can I download it directly from the webpage instead of using Google Cloud Drive

Have a nice day~

**Comment by SeanSiyang** [comment]
@marionacaros Can you help me?

**Comment by marionacaros** [comment]
oh you're right! I just tried through the [Google forms they provide](https://udayton.edu/engineering/research/centers/vision_lab/research/was_data_analysis_and_processing/dale.php) and the link they sent is not working anymore... You can get the dataset from [this link](https://drive.google.com/file/d/1o_dMm3Hsjh7wU8PZmzBS2Cy65DGUkMJT/view?usp=sharing) I hope it helps
